# Site settings
title: "#!/bin/sandipan"
description: > # this means to ignore newlines until "baseurl:"
  Programming & productivity.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://blog.sandipan.net" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
repository: srazzaque/srazzaque.github.io
